energy: 7
genie_n_events: 1000
run: 4
pdg: 16
start_step: 5
# The line below will be changed automatically by a program that calculates the number of GENIE events that produced a tau lepton
tau_n_events: 298
